### ISSUE TITLE
error 'An unknown scope was requested'

### ISSUE THREAD

**Issue by aarons2222** [andium/AmazonDRS#2]

**Comment by briancarbs** [comment]
Hey @aarons2222 have a little more detail on this? I'm assuming you've received this error while attempting to complete the [LWA authorization code grant process](https://github.com/andium/AmazonDRS#login-with-amazon-consent-requestauthorization-code-grant)? Ensure within your req that you're using scope 'dash:replenish'. It's sent within your json contained in the scope_data argument.

Another possible "gotchya" is that within your LWA Security profile you've failed to enter your 'allowed origin URI/callback'. 

If you can get some more detail about when and where you're receiving this I'd be happy to help!

--Carbs
